#yaml file for GitHub Actions to build and push a Docker image to Azure Container Registry (ACR) when code is pushed to the main branch.
name: Build and push docker image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to ACR
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login netflixbackendwithdocker.azurecr.io \
        -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t netflixbackend .

    - name: Tag image
      run: |
        docker tag netflixbackend netflixbackendwithdocker.azurecr.io/netflixbackend:latest

    - name: Push image
      run: |
        docker push netflixbackendwithdocker.azurecr.io/netflixbackend:latest

docker tag netflixbackendwithdocker.azurecr.io/netflixbackendwithdocker:${{ github.run_number }}
docker push netflixbackendwithdocker.azurecr.io/netflixbackendwithdocker:${{ github.run_number }}